# Generated by Django 3.1.2 on 2020-11-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0003_auto_20201122_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
